### ISSUE TITLE
When the member cluster is removed, the deployment status does not change

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#2239]
**What happened**:
![image](https://user-images.githubusercontent.com/17962021/180376942-d86a3bb9-9977-4338-88ed-4dc051484389.png)

**What you expected to happen**:

Currently, no member cluster has nginx deployment. So , i think the nginx deployment should display `0/2`  in karmada

**How to reproduce it (as minimally and precisely as possible)**:

1. create a nginx deployment
2. create a pp
3. remove the member cluster
4. check nginx deployment status

nginx.yaml
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: docker.m.daocloud.io/nginx:1.14.2
        name: nginx
````

pp.yaml
``` yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:  master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): master
- Others:

**Comment by dddddai** [comment]
I remember there was the same issue https://github.com/karmada-io/karmada/issues/768 and that was fixed
Looks like the cause is https://github.com/karmada-io/karmada/pull/1366

/assign

**Comment by XiShanYongYe-Chang** [comment]
Hi @chaunceyjiang, the bugfix has been merged, you can have a retry.

/close

**Comment by RainbowMango** [comment]
> Hi @chaunceyjiang, the bugfix has been merged, you can have a retry.

If afraid #2249 didn't solve this problem. This issue probably will be fixed along with #1995.

**Comment by chaunceyjiang** [comment]
OK, I'll try again
