### ISSUE TITLE
Failed to propagate a Pod kind to a member cluster

### ISSUE THREAD

**Issue by luotian-github** [karmada-io/karmada#734]
Propagate a Pod kind from the karmada host to a member cluster, the Pod is always in Pending.
![图片](https://user-images.githubusercontent.com/28591924/133393492-a48f86a1-113c-4977-ae36-44fa21a06810.png)

In the member cluster, found the pod failed to mount /var/run/secrets/kubernetes.io/serviceaccount from default-token-qv4ws

![图片](https://user-images.githubusercontent.com/28591924/133393918-fd62016b-c2c7-42fb-9353-9cd235f67c8f.png)

There is no secret default-token-qv4ws in the member cluster
![图片](https://user-images.githubusercontent.com/28591924/133394096-afe946be-abce-4db1-a00d-6023a61f21db.png)

The default-token-qv4ws is in the host cluster (control plane)
![图片](https://user-images.githubusercontent.com/28591924/133394967-45c0fb96-f4e0-4ee3-bff6-a3181dc8d88e.png)

The karmada version is v0.7.0-dirty  GitCommit:"33a214b6393d0800de147b698d31a7d21585e10d"

**Comment by XiShanYongYe-Chang** [comment]
Hi @luotian-github, thanks for trying karmada.

This bug has been resolved by #646 , you can have a retry with `master` branch, or `cherry-pick` this commint.

**Comment by XiShanYongYe-Chang** [comment]
Hi @luotian-github , did you try again, any problems?

**Comment by luotian-github** [comment]
Still encountered this problem, I'm using the version 0.8.0 c37bedc1 now
![图片](https://user-images.githubusercontent.com/28591924/134655335-0da5c2c2-a927-463f-aaa9-f7af38901dd0.png)

**Comment by XiShanYongYe-Chang** [comment]
Is it convenient for you to share your yaml? i will try it on my side.

**Comment by luotian-github** [comment]
pod yaml:
apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    app: nginxpod
spec:
  containers:
  - image: nginx:v1.17.5-1
    name: nginx

propagation yaml:
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation-pod
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
      name: nginxpod
  placement:
    clusterAffinity:
      clusterNames:
        - board-1

my clusters:
![图片](https://user-images.githubusercontent.com/28591924/134894067-e43c10bc-ee16-4382-afa5-18991bcdb6ed.png)

**Comment by XiShanYongYe-Chang** [comment]
> Still encountered this problem, I'm using the version 0.8.0 [c37bedc](https://github.com/karmada-io/karmada/commit/c37bedc1cfe5a98b47703464fed837380c90902f) now

I'm sorry, I misread it.

The `v0.8.0` has not resolve this issue, you need to cherry-pick a4bc72c03cf831478bd6bd312e38e298882284c1 with #646 .

**Comment by XiShanYongYe-Chang** [comment]
Any progress?

**Comment by XiShanYongYe-Chang** [comment]
Versions later than v0.9.0 have fixed this issue.

/close
