### ISSUE TITLE
Failed to startup with local karmada cluster due to : "pkg/controllers/hpa/hpa_controller.go:145:15: undefined: workv1alpha1"

### ISSUE THREAD

**Issue by AaronLinOops** [karmada-io/karmada#783]
**Please provide an in-depth description of the question you have**:

Follow the readme to startup a local karmada cluster, it failed with message:

```
Preparing kindClusterConfig in path: /var/folders/9d/bb6ggdm177j25q40yf5d50dm0000gn/T/tmp.eMHkLRIg
Creating cluster karmada-host
Creating cluster member1
Creating cluster member2
Creating cluster member3
CGO_ENABLED=0 GOOS=linux go build \
		-ldflags "-X github.com/karmada-io/karmada/pkg/version.gitVersion=v0.8.0-184-g3f275c53-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=3f275c53e6852a0217516bd585a0b915f5116e9a -X github.com/karmada-io/karmada/pkg/version.gitTreeState="dirty" -X github.com/karmada-io/karmada/pkg/version.buildDate=2021-09-30T10:39:32Z" \
		-o karmada-controller-manager \
		cmd/controller-manager/controller-manager.go
# github.com/karmada-io/karmada/pkg/controllers/hpa
pkg/controllers/hpa/hpa_controller.go:145:15: undefined: workv1alpha1
```

**What do you think about this question?**:

I have no idea.

**Environment**:

kind v0.11.1 / kindest/node:v1.21.1
go1.16.4 
darwin/amd64

- Karmada version:

master

**Comment by XiShanYongYe-Chang** [comment]
@AaronLinOops Just a little problem, has been fixed, can you try again?

**Comment by AaronLinOops** [comment]
> @AaronLinOops Thanks for spotting, this is a compile issue and has been fixed in favor of #782 .

Yes，it works, thanks, bros. Perhaps you guys could improve the CI/CD process to ensure that the master branch can be compiled properly at any time.

**Comment by RainbowMango** [comment]
The CI process can cover the compile, but this still happens when the PR is not rebased on the latest master branch.
This is an annoying thing :(
